### ISSUE TITLE
RISC-V 工具链 & QEMU 虚拟机 | JohnWestonNull.github.io

### ISSUE THREAD

**Issue by jwnhy** [jwnhy/jwnhy.github.io#2]
https://johnwestonnull.github.io/riscv/toolchain

**Comment by macromogic** [comment]
`glibc-2.31`及以上版本中，函数`stime()`被移除，这会导致BusyBear编译失败。解决方案是将该函数调用替换成新的`clock_settime()`。详见[此处](https://git.busybox.net/busybox/commit/?id=d3539be8f27b8cbfdfee460fe08299158f08bcd9)。
